ARG PIHOLE_VERSION
FROM pihole/pihole:nightly

# Default versions
ENV UNBOUND_VERSION=1.17.0

RUN apt update && apt install -y build-essential && apt install net-tools \
    && apt install wget && apt install -y -f openssh-server
RUN apt install -y libssl-dev && apt install -y libexpat1-dev
RUN apt-get install -y bison && apt-get install -y flex

RUN useradd unbound && mkdir /var/lib/unbound

# Install Unbound

RUN wget https://nlnetlabs.nl/downloads/unbound/unbound-${UNBOUND_VERSION}.tar.gz \
    && tar -xf unbound-${UNBOUND_VERSION}.tar.gz -C / && rm unbound-${UNBOUND_VERSION}.tar.gz

RUN cd unbound-${UNBOUND_VERSION} && ./configure && make && make install \
    && cd / && rm -rf unbound-${UNBOUND_VERSION}

COPY lighttpd-external.conf /etc/lighttpd/external.conf
COPY unbound-pihole.conf /etc/unbound/unbound.conf.d/pi-hole.conf
COPY 99-edns.conf /etc/dnsmasq.d/99-edns.conf
RUN mkdir -p /etc/services.d/unbound
COPY unbound-run /etc/services.d/unbound/run
RUN chmod ug+x /etc/services.d/unbound/run

RUN wget https://www.internic.net/domain/named.root -qO- | tee /var/lib/unbound/root.hints
RUN chown -R unbound:unbound /var/lib/unbound/root.hints

# install pihole-cloudsync (from repository by Steve Jenkins)

RUN mkdir -p /usr/local/bin/pihole-cloudsync
COPY pihole-cloudsync/pihole-cloudsync /usr/local/bin/pihole-cloudsync
RUN chmod +x /usr/local/bin/pihole-cloudsync/pihole-cloudsync

ENTRYPOINT ./s6-init


