ARG PIHOLE_VERSION
FROM pihole/pihole:nightly

COPY debian_testing.list /etc/apt/sources.list.d/

RUN apt update && apt install -y -f openssl \ 
    && apt install -y -f unbound* && apt install -y -f net-tools \
    && apt install -y -f wget && apt install -y -f openssh-server

RUN mkdir -p /var/log/unbound
RUN chown -R unbound:unbound /var/log/unbound
COPY lighttpd-external.conf /etc/lighttpd/external.conf 
COPY unbound-pihole.conf /etc/unbound/unbound.conf.d/pi-hole.conf
COPY 99-edns.conf /etc/dnsmasq.d/99-edns.conf
RUN mkdir -p /etc/services.d/unbound
COPY unbound-run /etc/services.d/unbound/run

COPY unbound-logrotate /etc/unbound/logrotate
RUN chmod 644 /etc/unbound/logrotate

COPY unbound-cron /etc/cron.d/unbound
RUN chmod 644 /etc/cron.d/unbound

COPY unbound-package-helper /usr/lib/unbound/package-helper
RUN chmod 755 /usr/lib/unbound/package-helper

RUN wget https://www.internic.net/domain/named.root -qO- | tee /var/lib/unbound/root.hints
RUN chown -R unbound:unbound /var/lib/unbound/root.hints

# install pihole-cloudsync (from repository by Steve Jenkins)

RUN mkdir -p /usr/local/bin/pihole-cloudsync
COPY pihole-cloudsync/pihole-cloudsync /usr/local/bin/pihole-cloudsync
RUN chmod +x /usr/local/bin/pihole-cloudsync/pihole-cloudsync

LABEL org.opencontainers.image.authors="Dick Pluim" \
      org.opencontainers.image.title="***/pihole-unbound" \
      org.opencontainers.image.description="Run Pi-Hole + Unbound on Docker" \
      org.opencontainers.image.url="https://github.com/***/docker-pihole-unbound" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.source="https://github.com/***/docker-pihole-unbound"

ENTRYPOINT ./s6-init

