name: Build and push latest

on:
  # cron job to trigger the build on any push to master
  push:
    branches:
      - 'main'
    paths:
      - 'pihole-unbound/VERSION'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manually trigger latest build'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


#  schedule:
  # cron job to trigger the build dialy (time in UTC)
#    - cron:  '0 4 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of pihole docker
        uses: rez0n/actions-github-release@main
        id: pihole_version
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "pi-hole/docker-pi-hole"
          type: "latest"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          build-args: PIHOLE_VERSION=${{ steps.pihole_version.outputs.release }}
          context: "{{defaultContext}}:pihole-unbound/"
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: pluim003/pihole-unbound:latest,pluim003/pihole-unbound:${{ steps.pihole_version.outputs.release }}
